/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bo_Demo */

#ifndef _Included_com_bo_Demo
#define _Included_com_bo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bo_Demo
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bo_Demo_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
